spring:
  application:
    name: TaskManagementSystem
  datasource:
    url: jdbc:h2:mem:task_management_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  spring:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    path: /swagger

